#!/bin/bash
#
# start systemd in a VRF context

VRF=$1

XDG_RUNTIME_DIR=/run/systemd-${VRF}
export XDG_RUNTIME_DIR

# default context if not given is management vrf.
# don't assume management vrf = "mgmt", but allow
# mgmt arg to this script to mean management vrf

if [ -z "${VRF}" -o "${VRF}" = "mgmt" ]; then
	/usr/cumulus/bin/cl-vrf mgmt set $$ || exit 1
else
	/usr/cumulus/bin/cl-vrf task set ${VRF} $$ || exit 1
fi

exec /bin/systemd --user 
