#!/bin/bash

# Install FIB rules for DNS servers

# priority of FIB rules. Needs to be before (lower prio)
# VRF rules
PRIO=99

VERBOSE=0

################################################################################
# logging

function log_cmd
{
	if [ $VERBOSE -eq 1 ]; then
		echo "vrf-dns-helper: $*"
	fi
}

################################################################################
# TO-DO: distinguish IPv4 and IPv6 DNS

function configure_dns_server
{
	dns=$1
	table=$2

	# does rule already exist?
	ip ru ls | grep -q "to ${dns} lookup ${table}"
	[ $? -eq 0 ] && return 0

	log_cmd "ip rule add to ${dns} prio ${PRIO}"
	ip rule add to ${dns} prio ${PRIO}
}

function remove_dns_server
{
	dns=$1
	table=$2

	# simpler to just do remove command and not worry about ENOENT error
	log_cmd "ip rule del to ${dns} lookup ${table} prio ${PRIO}"
	ip rule del to ${dns} lookup ${table} prio ${PRIO} 2>/dev/null

	return 0
}

function vrf_delete
{
	local vrf=$1
	local mgmt

	# For now only going to install DNS rules for management VRF
	mgmt=$(/usr/cumulus/bin/cl-vrf mgmt dev)
	[ "$vrf" != "$mgmt" ] && return 0

	# since we are only handling mgmt VRF could delete all rules with
	# our priority which handles DNS changes between VRF create & delete
	while read ns ip tmp
	do
		[ "$ns" != "nameserver" ] && continue
		# simpler to just do remove command and not worry about
		# ENOENT error
		log_cmd "ip rule del to ${dns} prio ${PRIO}"
		ip rule del to ${dns} prio ${PRIO} 2>/dev/null
	done < /etc/resolv.conf
}

function vrf_create
{
	local vrf=$1
	local tbid=$2
	local mgmt

	if [ -z "$tbid" ]; then
		return 1
	fi

	# For now only going to install DNS rules for management VRF
	mgmt=$(/usr/cumulus/bin/cl-vrf mgmt name)
	[ "$vrf" != "$mgmt" ] && return 0

	while read ns ip tmp
	do
		[ "$ns" != "nameserver" ] && continue
		configure_dns_server $ip $tbid
	done < /etc/resolv.conf
}

################################################################################
# main

# enable verbose logging?
if [ "$1" = "-v" ]; then
        VERBOSE=1
        VERBARG="-v"
        shift
fi

ACTION=$1
shift
case "$ACTION" in
	dns_add) configure_dns_server $*;;
	dns_del) remove_dns_server $*;;
	create)  vrf_create $*;;
	delete)  vrf_delete $*;;
	*) exit 1;;
esac
