#!/bin/bash

set -e

DIVERT_DIR=/usr/share/cumulus-vrf

# uninstall alternatives to ping and traceroute
for f in /usr/bin/traceroute /usr/sbin/traceroute /usr/bin/traceroute6 /bin/ping /bin/ping6
do
	[ ! -e ${DIVERT_DIR}/${f} ] && continue
	dpkg-divert --remove ${f}
	rm -f ${f}
	mv -f ${DIVERT_DIR}/${f} ${f}
done

# undo package diverts
for f in /etc/skel/.bashrc /etc/bash.bashrc
do
	[ ! -e ${DIVERT_DIR}/${f} ] && continue
	dpkg-divert --remove ${f}
	rm -f ${f}
	mv -f ${DIVERT_DIR}/${f} ${f}
done

#DEBHELPER#

exit 0
