#!/bin/bash

set -e

DIVERT_DIR=/usr/share/cumulus-vrf

# uninstall alternatives to ping and traceroute
for f in /usr/bin/traceroute /usr/sbin/traceroute /usr/bin/traceroute6 /bin/ping /bin/ping6
do
	[ ! -e ${DIVERT_DIR}/${f} ] && continue
	dpkg-divert --remove ${f}
	rm -f ${f}
	mv -f ${DIVERT_DIR}/${f} ${f}
done

# undo package diverts
for f in /etc/skel/.bashrc /etc/bash.bashrc
do
	[ ! -e ${DIVERT_DIR}/${f} ] && continue
	dpkg-divert --remove ${f}
	rm -f ${f}
	mv -f ${DIVERT_DIR}/${f} ${f}
done

# remove libpam-script config
VRF_PAM_SCRIPT=/usr/share/cumulus-vrf/libpam-script
PAM_SCRIPT=/usr/share/libpam-script
rm -f ${PAM_SCRIPT}/pam-script.d/vrf_pam_ses_open

for f in pam_script_acct pam_script_auth pam_script_ses_open pam_script_ses_close pam_script_passwd
do
	g=${PAM_SCRIPT}/$f
	[ ! -s $g ] && continue

	l=$(readlink $g)
	case "$l" in
		*vrf*) rm -f $g;;
	esac
done

#DEBHELPER#

exit 0
