#!/bin/bash

# Install FIB rules for DNS servers

# priority of FIB rules. Needs to be before (lower prio)
# VRF rules
PRIO=99

PROG=${0##*/}
VERBOSE=0

################################################################################
# logging

function log_cmd
{
	if [ $VERBOSE -eq 1 ]; then
		echo "${PROG}: $*"
	fi
}

################################################################################
# TO-DO: distinguish IPv4 and IPv6 DNS

function configure_dns_server
{
	local dns=$1
	local table=$2

	# does rule already exist?
	# TO-DO: table arg is a number, 'ip ru' always converts
	#        to text if an id to name exists
	ip ru ls | grep -q "from all to ${dns} lookup "
	[ $? -eq 0 ] && return 0

	log_cmd "ip rule add to ${dns} prio ${PRIO}"
	ip rule add to ${dns} lookup ${table} prio ${PRIO}
}

function remove_dns_server
{
	local dns=$1
	local table=$2

	# simpler to just do remove command and not worry about ENOENT error
	log_cmd "ip rule del to ${dns} lookup ${table} prio ${PRIO}"
	ip rule del to ${dns} lookup ${table} prio ${PRIO} 2>/dev/null

	return 0
}

function verify_dns_server
{
	local dns=$1
	local table=$2
	local tmpfile=$3	

	echo

	grep -q "from all to ${dns} lookup ${table}" ${tmpfile}
	if [ $? -eq 0 ]; then
		echo "Rule for dns server ${dns} exists with table ${table}"
		sed -ie "/from all to ${dns} lookup ${table}/d" ${tmpfile}
		return 0
	fi

	grep -q "from all to ${dns} lookup " ${tmpfile}
	if [ $? -eq 0 ]; then
		echo "Rule for dns server ${dns} exists but table match failed"
		sed -ie "/from all to ${dns} lookup /d" ${tmpfile}
		return 0
	fi

	echo "No FIB rule for dns server ${dns}"
	return 0
}

################################################################################
#

function vrf_delete
{
	local vrf=$1
	local mgmt

	# For now only going to install DNS rules for management VRF
	mgmt=$(mgmt-vrf name)
	[ "$vrf" != "$mgmt" ] && return 0

	# since we are only handling mgmt VRF could delete all rules with
	# our priority which handles DNS changes between VRF create & delete
	while read ns ip tmp
	do
		[ "$ns" != "nameserver" ] && continue
		# simpler to just do remove command and not worry about
		# ENOENT error
		log_cmd "ip rule del to ${dns} prio ${PRIO}"
		ip rule del to ${dns} prio ${PRIO} 2>/dev/null
	done < /etc/resolv.conf
}

function vrf_create
{
	local vrf=$1
	local tbid=$2
	local mgmt

	if [ -z "$tbid" ]; then
		return 1
	fi

	# For now only going to install DNS rules for management VRF
	mgmt=$(mgmt-vrf name)
	[ "$vrf" != "$mgmt" ] && return 0

	while read ns ip tmp
	do
		[ "$ns" != "nameserver" ] && continue
		configure_dns_server $ip $tbid
	done < /etc/resolv.conf
}

function vrf_verify
{
	local mgmt_name

	# For now only dealing with Management VRF
	mgmt-vrf status >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "Management VRF not enabled."
		return 0
	fi
	mgmt_name=$(mgmt-vrf name)

	# get a cache of DNS entries
	tmpfile=$(mktemp /tmp/vrf.XXXXXXXX)
	ip ru ls | egrep "^${PRIO}:" >> $tmpfile

	while read ns ip tmp
	do
		[ "$ns" != "nameserver" ] && continue
		verify_dns_server ${ip} ${mgmt_name} ${tmpfile}
	done < /etc/resolv.conf

	if [ -s ${tmpfile} ]; then
		echo
		echo "Extra FIB rules exist at DNS priority:"
		cat ${tmpfile}
	fi

	rm -f ${tmpfile}
}

################################################################################
# main

# enable verbose logging?
if [ "$1" = "-v" ]; then
        VERBOSE=1
        shift
fi

ACTION=$1
shift
case "$ACTION" in
	dns_add) configure_dns_server $*;;
	dns_del) remove_dns_server $*;;
	create)  vrf_create $*;;
	delete)  vrf_delete $*;;
	verify)  vrf_verify;;
	*) exit 1;;
esac
